# .github/workflows/hello.yml
name: Hello World Pipeline

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print message
        run: echo "🚀 CI/CD pipeline is working!"
      
      - name: Show files
        run: ls -la
      
      - name: Show date
        run: date
